services:
  - type: web
    name: resume-analyzer
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"